# Generated by Django 5.2 on 2025-05-04 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('race_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'race', blank=True, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ratings.race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ratings.user')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ratings.season'),
        ),
        migrations.AddField(
            model_name='race',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ratings.track'),
        ),
    ]
