# Generated by Django 5.2 on 2025-05-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_race_season_track_rating_race_season_race_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='pk',
        ),
        migrations.AddField(
            model_name='rating',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'race'), name='rating-user_relation'),
        ),
    ]
