# Generated by Django 5.2 on 2025-05-07 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_remove_rating_pk_rating_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('full_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('driver_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='number_of_laps',
            field=models.IntegerField(default=69),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.user'),
        ),
        migrations.AddField(
            model_name='race',
            name='drivers',
            field=models.ManyToManyField(to='ratings.driver'),
        ),
        migrations.CreateModel(
            name='Starting_grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_position', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ratings.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ratings.race')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('race', 'starting_position'), name='the_how-tf-do-two-drivers-start-on-the-same-position_constraint')],
            },
        ),
    ]
