# Generated by Django 5.2 on 2025-05-07 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_driver_race_number_of_laps_alter_rating_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_of_race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='race_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ratings.type_of_race'),
            preserve_default=False,
        ),
    ]
