# Generated by Django 5.2 on 2025-05-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_type_of_race_race_race_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='number_of_laps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_number',
            field=models.IntegerField(null=True),
        ),
    ]
